
[tools]
# fd is a dependency of telescope and fzf-lua
"ubi:sharkdp/fd" = "10.3.0"
"ubi:junegunn/fzf" = "0.66.1"
"ubi:BurntSushi/ripgrep" = { version = "15.1.0", exe = "rg" }
"ubi:JohnnyMorganz/stylua" = "2.3.0"
actionlint = "1.7.8"
