std = "vim"
exclude = [
  "packages/integration-tests/test-environment/.repro/*",
  "packages/integration-tests/test-environment/multicursor-file.lua",
  "packages/integration-tests/test-environment/test-setup.lua",
]
