name: reviewdog eslint
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: pnpm/action-setup@v4.0.0
      - uses: actions/setup-node@v4.0.4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - run: pnpm install

      - uses: reviewdog/action-eslint@v1.32.0
        with:
          workdir: packages/integration-tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review # Change reporter.
